import UIKit

class Common {
    
    static let loginUrl = "http://192.168.107.90:89/login"
    static let mainItemUrl = "http://192.168.107.90:89/forms/"
    static let formItemUrl = "http://192.168.107.90:89/form_elements/"
    static let Register_url = "https://civilsafety.edu.au/appinquire/"
    static let FormItemOption_url = "http://192.168.107.90:89/form_elements_options"
    
    static let error = "Error"
    static let yesBtn = "Yes"
    static let nobtn = "No"
    static let offlineLb = "It is currently offline."
    
    static let BASE = UIColor(red: 0.0, green: 44/255, blue: 115/255, alpha: 1.0)
    
    static func NoticeAlert(vc: UIViewController, Ntitle: String, Nmessage: String){
        let dialogMessage = UIAlertController(title: Ntitle, message: Nmessage, preferredStyle: .alert)
        let ok = UIAlertAction(title: "OK", style: .default, handler: { (action) -> Void in
            dialogMessage.dismiss(animated: true, completion: nil)
         })
        
        dialogMessage.addAction(ok)
        vc.present(dialogMessage, animated: true, completion: nil)
    }
    
    static let countryArray:[String] = [
        "United States"
        ,"United Kingdom"
        ,"Canada"
        ,"Australia"
        ,"Netherlands"
        ,"France"
        ,"Germany"
        ,"-------"
        ,"Afghanistan"
        ,"Albania"
        ,"Algeria"
        ,"Andorra"
        ,"Antigua and Barbuda"
        ,"Argentina"
        ,"Armenia"
        ,"Austria"
        ,"Azerbaijan"
        ,"Bahamas"
        ,"Bahrain"
        ,"Bangladesh"
        ,"Barbados"
        ,"Belarus"
        ,"Belgium"
        ,"Belize"
        ,"Benin"
        ,"Bermuda"
        ,"Bhutan"
        ,"Bolivia"
        ,"Bosnia and Herzegovina"
        ,"Botswana"
        ,"Brazil"
        ,"Brunei"
        ,"Bulgaria"
        ,"Burkina Faso"
        ,"Burundi"
        ,"Cambodia"
        ,"Cameroon"
        ,"Cape Verde"
        ,"Cayman Islands"
        ,"Central African Republic"
        ,"Chad"
        ,"Chile"
        ,"China"
        ,"Colombia"
        ,"Comoros"
        ,"Congo"
        ,"Costa Rica"
        ,"Côte d'Ivoire"
        ,"Croatia"
        ,"Cuba"
        ,"Cyprus"
        ,"Czech Republic"
        ,"Denmark"
        ,"Djibouti"
        ,"Dominica"
        ,"Dominican Republic"
        ,"East Timor"
        ,"Ecuador"
        ,"Egypt"
        ,"El Salvador"
        ,"Equatorial Guinea"
        ,"Eritrea"
        ,"Estonia"
        ,"Ethiopia"
        ,"Fiji"
        ,"Finland"
        ,"Gabon"
        ,"Gambia"
        ,"Georgia"
        ,"Ghana"
        ,"Gibraltar"
        ,"Greece"
        ,"Grenada"
        ,"Guatemala"
        ,"Guernsey"
        ,"Guinea"
        ,"Guinea-Bissau"
        ,"Guyana"
        ,"Haiti"
        ,"Honduras"
        ,"Hong Kong"
        ,"Hungary"
        ,"Iceland"
        ,"India"
        ,"Indonesia"
        ,"Iran"
        ,"Iraq"
        ,"Ireland"
        ,"Israel"
        ,"Italy"
        ,"Jamaica"
        ,"Japan"
        ,"Jordan"
        ,"Kazakhstan"
        ,"Kenya"
        ,"Kiribati"
        ,"North Korea"
        ,"South Korea"
        ,"Kuwait"
        ,"Kyrgyzstan"
        ,"Laos"
        ,"Latvia"
        ,"Lebanon"
        ,"Lesotho"
        ,"Liberia"
        ,"Libya"
        ,"Liechtenstein"
        ,"Lithuania"
        ,"Luxembourg"
        ,"Macedonia"
        ,"Madagascar"
        ,"Malawi"
        ,"Malaysia"
        ,"Maldives"
        ,"Mali"
        ,"Malta"
        ,"Marshall Islands"
        ,"Mauritania"
        ,"Mauritius"
        ,"Mexico"
        ,"Micronesia"
        ,"Moldova"
        ,"Monaco"
        ,"Mongolia"
        ,"Montenegro"
        ,"Morocco"
        ,"Mozambique"
        ,"Myanmar"
        ,"Namibia"
        ,"Nauru"
        ,"Nepal"
        ,"New Zealand"
        ,"Nicaragua"
        ,"Niger"
        ,"Nigeria"
        ,"Norway"
        ,"Oman"
        ,"Pakistan"
        ,"Palau"
        ,"Palestine"
        ,"Panama"
        ,"Papua New Guinea"
        ,"Paraguay"
        ,"Peru"
        ,"Philippines"
        ,"Poland"
        ,"Portugal"
        ,"Puerto Rico"
        ,"Qatar"
        ,"Romania"
        ,"Russia"
        ,"Rwanda"
        ,"Saint Kitts and Nevis"
        ,"Saint Lucia"
        ,"Saint Vincent and the Grenadines"
        ,"Samoa"
        ,"San Marino"
        ,"Sao Tome and Principe"
        ,"Saudi Arabia"
        ,"Senegal"
        ,"Serbia and Montenegro"
        ,"Seychelles"
        ,"Sierra Leone"
        ,"Singapore"
        ,"Slovakia"
        ,"Slovenia"
        ,"Solomon Islands"
        ,"Somalia"
        ,"South Africa"
        ,"Spain"
        ,"Sri Lanka"
        ,"Sudan"
        ,"Suriname"
        ,"Swaziland"
        ,"Sweden"
        ,"Switzerland"
        ,"Syria"
        ,"Taiwan"
        ,"Tajikistan"
        ,"Tanzania"
        ,"Thailand"
        ,"Togo"
        ,"Tonga"
        ,"Trinidad and Tobago"
        ,"Tunisia"
        ,"Turkey"
        ,"Turkmenistan"
        ,"Tuvalu"
        ,"Uganda"
        ,"Ukraine"
        ,"United Arab Emirates"
        ,"Uruguay"
        ,"Uzbekistan"
        ,"Vanuatu"
        ,"Vatican City"
        ,"Venezuela"
        ,"Vietnam"
        ,"Yemen"
        ,"Zambia"
        ,"Zimbabwe"
    ]
}
